# Generated by Django 4.1.7 on 2023-05-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0008_question_modify_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="modify_count",
            field=models.IntegerField(default=0),
        ),
    ]
